[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"
async-std = "1.12.0"
serde = "1.0.197"
uuid = { version = "1.8.0", features = ["v4"] }
